### ISSUE TITLE
Inviting team members

### ISSUE THREAD

**Issue by martinyoo** [worldoss/ocean#1]

**Comment by martinyoo** [comment]
@worldoss/all 께서는  @paulkimds 과 저에게 GitHub 계정을 알려주시면

https://github.com/orgs/worldoss/teams/all/members 에 초대하겠습니다.

**Comment by paulkimds** [comment]
제 권한 제한으로 한양대학교 연구팀은 'team member'로 등록하는 대신, 모두 'collaborator'로 등록하였습니다.

**Comment by martinyoo** [comment]
Team 이 상위팀, 하위팀의 2단계가 있습니다.

'all' 이라는 Team 밑에 'hanyang' 과 'spri' 2개 팀이  있습니다.


한양대학교 연구팀을 'hanyang' 팀 밑으로 옮겨주시기 바랍니다^^

**Comment by paulkimds** [comment]
@martinyoo 2개의 하위 팀('spri'과 'hanyang')을 확인하고, 해당 팀의 'member'로 옮기려 하였으나, 첨부된 이미지와 같이  'organization' 의 'owner'만이 팀원을 추가 및 구성할 수 있는 것 같습니다. 
저는 'organization' 수준에서는 'member' 권한이라 불가능한 것 같습니다. 한양대 연구원 모두를 팀으로 이동하는 일이 번거로우실 것 같아 우선 'write' 권한까지 부여한  'collaborator'으로 등록해 두었습니다. 
과제 진행동안 'organization'에서의 제 권한을  'owner' 으로 부여해 주시는 것도 방안이 될 것 같습니다. ^^
![image](https://user-images.githubusercontent.com/18477915/28072535-52feae40-668e-11e7-9e38-a9adf878d4a6.png)

**Comment by martinyoo** [comment]
@paulkimds  제안에 따라 owner 권한을 부여하였습니다.

**Comment by paulkimds** [comment]
한양대학교 참여 연구원 모두가 'hanyang' 팀으로 이동이 완료되어 본 이슈는 'close' 하겠습니다.
