### ISSUE TITLE
Learning github

### ISSUE THREAD

**Issue by martinyoo** [worldoss/ocean#2]
오픈소스 개발자 이자, 깃허브 전문강사에게 강의를 듣는 시간을 가지겠습니다.

시간은 7/19 오후3시~6시 입니다.

구체적인 강의내용은 7/12 회의에서 논의하겠습니다.

송태웅 강사소개 : 
https://kosslab.kr/koss/opensft/introduceView.php?ordinal=3&idx=40

------------------------------------------------------------------
보낸 사람: 유호석
보낸 날짜: 2017년 7월 11일 화요일 오후 10:35
받는 사람: Taeung Song
제목: RE: 깃허브 사용법 자문&강의 요청

네, 제안하신대로 다음 주 3시간을 한꺼번에 할애하는 것으로 하겠습니다.

실습을 먼저하고 사례를 관찰하도록 순서를 바꾸는 것은 내일 회의 후 말씀드리겠습니다.

초청에 응해주셔서 감사합니다.

------------------------------------------------------------------

보낸 사람: Taeung Song
보낸 날짜: 2017년 7월 11일 화요일 오후 3:57
받는 사람: 유호석
제목: Re: 깃허브 사용법 자문&강의 요청

안녕하세요. 유호석 선임연구원님

**개발자들이 Github을 사용하는 패턴을 이해하는게 중요한 목적이군요!
제 생각에는 1차,2차 내용을 반대로 하는게 더좋을것같다는 생각이 들었습니다.
아무래도 조금이라도 경험하고나서 실제사례를 들으면 왜그렇게 되는지 더 와닿아
하시는 경우가 많아서 의견드렸습니다.

   1차: Git/Github 실습
   2차: 실제 개발자들의 Git/Github 사용사례 살펴보기**

그리고 제가 7/26(수)에는 한국에 없습니다.
그래서 7/12(수), 7/19(수) 두차례로 아니면
혹시 다음주 한번에 3시간정도 할당이 될까요 ?

감사합니다
송태웅 드림

On 07/11/2017 03:28 PM, 유호석 wrote:
> 안녕하세요.
> 
> 작년11월에 제주도에서 명함 교환하고 인사한 적이 있습니다^^
> 
> 다름이 아니라, 저희 정책연구소에서 한양대와 공동으로 GitHub 데이터분석을 
> 거쳐 정책시사점을 도출하는 프로젝트를 하고 있습니다.
> 
> 이에 개발자가github을 주로 사용하는 패턴에 대해 정식으로 자문&강의를 2차 
> 례 정도정도 받았으면 합니다.
> 
> 1차는 일단 저희 프로젝트팀을 대상으로 일반적인 깃허브 개발자가 많이 사용 
> 하는 기능을 소개해주시면 되고,
> 
> 2차는 실제 깃허브 사용법을 실습 또는 데모를 통해 익혔으면 합니다.
> 
> 저희가 선호하는 시간은 매주 정기회의가 수요일4시~6시라서 이 시간 동안인 
> 5~6시 사이에 연구소에 한번 와서 소개해 주시면 가장 좋습니다.
> 
> 이에 다음주 오후4시가 가능하신지 문의드립니다.
> 
> 혹시 이 시간이 안되면 다른 시간&장소도 가능합니다., 강사님이 선호하는 대 
> 략적인 시간과 지역을 편하게 알려주시면 됩니다.
> 
> 감사합니다.
> 
> 소프트웨어報國!!
> 
> 유호석
> 소프트웨어정책연구소 선임연구원
> Mobile : 010-2667-5417
> Office : 031-739-7351
> Email : hsy@spri.kr
> Adrress : 경기도 성남시 분당구 대왕판교로712번길 글로벌R&D센터 연구동A 4 
> 층(우:463-400)
>

**Comment by martinyoo** [comment]
실습을 먼저하고 사례를 안내받는 것으로 강사에게 요청하겠습니다.

- 시간 : 7/19 수요일 3시~6시
- 장소 :  한양대 캠퍼스 실습실 입니다.

**Comment by paulkimds** [comment]
다음 주 전문가 초청 강의와 관련하여 장소를 안내하여 드립니다.

- 시간 : 7/19 수요일 3시~6시
- 장소 : 한양대학교 경영관(건물번호 706번), 지하203호
- 기타 : 주차지원 가능(행원파크 지하 주차장), 개별 실습용 컴퓨터는 강의실에 설치되어 있으며, 개인 노트북을 가져오실 경우 무선 인터넷 사용 가능

- 오시는 길과 주차장에 대한 상세 안내는 아래 링크와 지도를  참조하여 주시기 바랍니다.

[한양대학교 경영관 - 네이버 지도](http://map.naver.com/local/siteview.nhn?code=18775386)

![1](https://user-images.githubusercontent.com/18477915/28200662-74f8c3d4-68a8-11e7-90d6-4f4e9abd350f.png)
