### ISSUE TITLE
깃허브 소스 업로드 관련

### ISSUE THREAD

**Issue by dellabee** [worldoss/ocean#27]
소스 업로드 시 실행 가능한 패키지를 올려주시고 

가능하면 결과값(csv 파일 등)을 같이 올려주세요 ^^ 

감사합니다.

**Comment by rlrlaa123** [comment]
requirement.txt 파일에 필요한 패키지 목록을 올려드리겠습니다.

**Comment by rlrlaa123** [comment]
requirement.txt 파일은 일단 커밋해놨습니다.
5eff7322d660b98a6e0803a5b1c5f7836e629aa7

**Comment by rlrlaa123** [comment]
결과값 파일은 용량이 너무 커서 앞으로 Google Drive에 올려서 공유해서 업로드 하겠습니다. 
그리고, 드라이브 링크는 README.md 파일에 작성해놓겠습니다.

**Comment by dellabee** [comment]
알곘습니다. 그럼 이 이슈는 닫습니다.
