### ISSUE TITLE
Most Popular Github Project

### ISSUE THREAD

**Issue by dellabee** [worldoss/ocean#5]
안녕하세요. 강송희연구원입니다. 

우선 크롤러로 5500개를 가져와서, Top 1000을 발라내신것 같은데 

Repository 총 개수는 2백만개 이상이고, 

https://github.com/search?q=stars:>1&s=stars&type=Repositories 

해보시면, Most stars로 sort해서 보시면 2,014,592개 가 나옵니다. (3:20PM 기준)

매 순간 마다 결과는 달라지구요, 

Star 수로 할 것인지, Fork 수로 할 것인지, 조합해서 할 것인지에 대한 의사결정도 있어야 하겠고 

몇 개를 할 것인지도 의사결정이 있어야 하겠네요. 
(제안서에 Top 20%였던가요? )

**Comment by martinyoo** [comment]
@worldoss/all 오늘 회의에서 논의합시다

**Comment by rlrlaa123** [comment]
안녕하세요 5500개 크롤링한거는 제가 처음에 잘 몰라서 처음부터 크롤링 하던 값이라 pull request 에서 뺀 데이터고 제가
최종적으로 올린값은 데이터는 전체 결과값 중 Top 1000개 입니다

2017. 7. 12. 오후 3:23에 "Edda Kang" <notifications@github.com>님이 작성:

**Comment by dellabee** [comment]
리파지토리 선정과 관련하여 동일한 이슈가 있어서 이 이슈는 닫습니다
